#ifndef GAMESTATE_HPP
#define GAMESTATE_HPP

enum class GameState
{
	IN_PROGRESS = 0,
	CHECKMATE = 1,
	STALEMATE = 2,
	RESIGNATION = 3,
	TIMEOUT = 4,
	THREEFOLD_REPETITION = 5,
	FIFTY_MOVE_RULE = 6,
	INSUFFICIENT_MATERIAL = 7
};

#endif // GAMESTATE_HPP