#ifndef SPECIALMOVE_HPP
#define SPECIALMOVE_HPP

enum class SpecialMove
{
	NONE = 0,
	DOUBLE_PAWN_PUSH = 1,
	EN_PASSANT = 2,
	KINGSIDE_CASTLE = 3,
	QUEENSIDE_CASTLE = 4,
	PROMOTION = 5
};

#endif // SPECIALMOVE_HPP